principal/cliente/urls.py
from django.urls import path

from .views import ClienteCreateView
from .views import ClienteListView, ClienteUpdateView

app_name = 'cliente'
urlpatterns = [
    path('', ClienteCreateView.as_view(), name="create"),
    path('listar/', ClienteListView.as_view(), name="list"),
    path('alterar/<slug:slug>/', ClienteUpdateView.as_view(), name="update"),
    
]

principal/principal/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cliente.urls')),
]

principal/cliente/models.py
from datetime import datetime
import hashlib
import random

from django.db import models
from django.urls import reverse

class Cliente(models.Model):
    nome = models.CharField(('Nome'), max_length=70)
    cidade = models.CharField(('Cidade'), max_length=70, blank=True, null=True)
    tel_celular = models.CharField(('Telefone Celular'), max_length=13, blank=True, null=True)
    is_active = models.BooleanField(('Ativo'), default=True)
    slug = models.SlugField(max_length=100, blank=True, unique=True, null=True)
    email = models.EmailField(('E-mail'), blank=True, null=True)

    @property
    def get_list_url(self):
        return reverse('cliente:update',kwargs={'slug':self.slug})

    def gerar_hash(self):
        return hashlib.sha256(str(random.getrandbits(256)).encode('utf-8')).hexdigest()
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = self.gerar_hash()
        super(Cliente, self).save(*args, **kwargs)

    def __str__(self):
        return self.nome

class Dependente(models.Model):
    cliente = models.ForeignKey('Cliente',on_delete=models.PROTECT)
    nome = models.CharField(('Nome'), max_length=40)
    tel_celular = models.CharField(('Telefone Celular'), max_length=13, blank=True, null=True)
    email = models.EmailField(('E-mail'), blank=True, null=True)
    slug = models.SlugField(max_length=100, blank=True, unique=True, null=True)

    @property
    def get_list_url(self):
        return reverse('cliente:update',kwargs={'slug':self.slug})
    
    def gerar_hash(self):
        return hashlib.sha256(str(random.getrandbits(256)).encode('utf-8')).hexdigest()
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = self.gerar_hash()
        super(Dependente, self).save(*args, **kwargs)

    def __str__(self):
        return self.descricao

principal/cliente/forms.py
from django import forms
from django.forms import inlineformset_factory
from django.utils.translation import ugettext_lazy as _

from .models import Cliente, Dependente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        exclude = ('slug',)


class DependenteForm(forms.ModelForm):
    class Meta:
        model = Dependente
        exclude = ()

    tel_celular = forms.CharField(label="Telefone Celular", widget=forms.TextInput(
            attrs={'class': 'form-control mask_tel_celular'}), max_length=13, required=False)


DependenteFormSet = inlineformset_factory(Cliente, Dependente,
                                              fields=('nome','tel_celular','email'),
                                              form=DependenteForm, extra=1)

principal/cliente/views.py
from django.shortcuts import render
from django.db import transaction
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse
from django.http import Http404, JsonResponse
from django.contrib import messages


from .models import Cliente
from .forms import DependenteForm
from .forms import ClienteForm, DependenteFormSet



class ClienteListView(ListView):
    model = Cliente
    template_name = 'cliente/cliente_list.html'



class ClienteCreateView(CreateView):
    model = Cliente
    form_class = ClienteForm
    success_url = 'cliente:list'

    def get_context_data(self, **kwargs):
        context = super(ClienteCreateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['dependente_cliente'] = DependenteFormSet(self.request.POST)
        else:
            context['dependente_cliente'] = DependenteFormSet()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset_dependente = context['dependente_cliente']

        with transaction.atomic():
            self.object = form.save(commit=False)
            self.object.save()

            if formset_dependente.is_valid():
                formset_dependente.instance = self.object
                formset_dependente.save()


        return super(ClienteCreateView, self).form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'Não foi possível cadastrar')
        return super(ClienteCreateView, self).form_invalid(form)

    def get_success_url(self):
        messages.success(self.request, 'cadastrado com sucesso!!')
        return reverse(self.success_url)

class ClienteUpdateView(UpdateView):
    model = Cliente

    form_class = ClienteForm
    success_url = 'cliente:list'

    def get_object(self, queryset=None):
        slug = self.kwargs.get(self.slug_url_kwarg)
        try:
            obj = Cliente.objects.get(slug=slug)
        except:
            raise Http404("Cliente não localizado")
        return obj
    
    def get_context_data(self, **kwargs):
        context = super(ClienteUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['dependente_cliente'] = DependenteFormSet(self.request.POST, instance=self.object)
        else:
            context['dependente_cliente'] = DependenteFormSet(instance=self.object)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset_dependente = context['dependente_cliente']

        with transaction.atomic():
            self.object = form.save(commit=False)
            self.object.save()

            if formset_dependente.is_valid():
                formset_dependente.instance = self.object
                formset_dependente.save()
        return super(ClienteUpdateView, self).form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'Não foi possível alterar')
        return super(ClienteUpdateView, self).form_invalid(form)  

    def get_success_url(self):
        messages.success(self.request, 'Cliente alterado com sucesso')
        return reverse(self.success_url)

principal/cliente/templates/cliente/cliente_form.html
{% load staticfiles %}
{% load bootstrap4 %}
{% block content %}
    {% csrf_token %}
    {{ form.non_field_errors }}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<title>SmPy</title>
  </head>
  <body>
    <div class="container">
    <h1 class="text-center text-uppercase text-success bg-dark">Cadastro de cliente!!</h1>

   <br><br><br><br><br>
    <form class="form" role="form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-sm-4 form-group mb-4">
                {% bootstrap_field form.nome %}
            </div>
            <div class="col-sm-4 form-group mb-4">
                {% bootstrap_field form.cidade %}
            </div>
            <div class="col-sm-4 form-group mb-4">
                {% bootstrap_field form.tel_celular %}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 form-group mb-4">
                {% bootstrap_field form.is_active %}
            </div>
            <div class="col-sm-4 form-group mb-4">
                {% bootstrap_field form.email %}
            </div>
        </div>
        <br><br><br><br><br><br><br><br><br><br>
        <p class="text-center text-uppercase text-success bg-dark">Cadastrar Dependente</p>
        <div id="formSetAnexo" class="ibox-body" aria-expanded="true">

                {{ dependente_cliente.management_form }}
                {% for form in dependente_cliente.forms %}

                    <div class="{% cycle row1 row2 row3 row4 %} row formset_dependente_row">

                        {% for field in form.visible_fields %}

                            {# Incluindo os campos hidden do form #}
                            {% if forloop.first %}
                                {% for hidden in form.hidden_fields %}
                                    {{ hidden }}
                                {% endfor %}
                            {% endif %}

                            <div class="form-group col-sm-4">
                                {% bootstrap_field field %}
                                {{ field.errors.as_ul }}
                            </div>

                            {# Quando for a última volta do loop, inclui uma linha para separar o próximo form #}
                            {% if forloop.last %}
                                <div class="form-group col-sm-6">
                                    <hr>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endfor %}
        </div>
        <button type="submit" class="save btn btn-default">Salvar</button>
        <a class="btn btn-primary" href="{% url 'cliente:list' %}">Listar</a>
</form>
</div>
    <!-- Optional JavaScript -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="{% static 'formSet/jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $('.formset_dependente_row').formset({
            addText: 'Adicionar Dependente',
            deleteText: 'Remover Dependente',
            prefix: 'dependente_set'
        });
</script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>
{% endblock %}

principal/cliente/templates/cliente/cliente_list.html
{% load staticfiles %}
{% load bootstrap4 %}
{% block content %}
    {% csrf_token %}
    {{ form.non_field_errors }}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>SmPy</title>
  </head>
  <body>
    <div class="container">

    <br><br>
    <h1 class="text-center text-uppercase text-success bg-dark">Listagem</h1>
    <br><br>
    <table class="table">
        <thead class="thead-dark">
          <tr>            
            <th scope="col">Nome</th>
            <th scope="col">Cidade</th>
            <th scope="col">Celular</th>
            <th scope="col">Ativo</th>
            <th scope="col">E-mail</th>
            <th scope="col">Editar</th>
          </tr>
        </thead>
        <tbody>
            {% for cliente in object_list %}
                <tr>
                    <th>{{ cliente.nome }}</th>
                    <th>{{ cliente.cidade }}</th>
                    <th>{{ cliente.tel_celular }}</th>
                    <th>{% if cliente.is_active%} Sim {% else%} Não {% endif %}</th>
                    <th>{{ cliente.email }}</th>
                    <th>
                        <a class="btn btn-primary" href="{{ cliente.get_list_url }}">Alterar</a>
                    </th>
                </tr>
          {% endfor %}
        </tbody>
      </table>
    <a class="btn btn-success" href="{% url 'cliente:create' %}">Cadastar</a>
    <br><br>  
  </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>
{% endblock %}